---
title: "Crowding in L.A. County (2019)"
output: html_document
---

```{r include=FALSE}
library(tidyverse)
library(leaflet)
library(sf)
library(glue)
library(DT)
```

```{r include=FALSE}
shp = read_sf('data/processed/la-oc-tracts-2019.geojson')
# shp

data = read_csv('data/processed/crowding-tracts-history.csv')
# data

xwalk = read_csv('data/processed/tract-mapla-xwalk.csv')
# xwalk

joined = shp %>% 
  filter(str_detect(GISJOIN, 'G060037')) %>% 
  left_join(
    data %>% 
      filter(year == 2019) %>% 
      filter(str_detect(GISJOIN, 'G060037')) %>%
      left_join(
        xwalk %>%
          filter(year == 2019) %>%
          group_by(GISJOIN) %>%
          filter(pct.tract == max(pct.tract)) %>% 
          ungroup() %>% 
          select(GISJOIN, hood.name, pct.tract)
      ) %>% 
      mutate(
        pct = crowded / total,
        popup = glue('tract id: {str_sub(GISJOIN, start = 9)}<br />
                     hood: {hood.name} ({round(pct.tract * 100, 1)}%)<br />
                     crowding rate: {round(pct * 100, 1)}%<br />
                     total: {total}<br />
                     crowded: {crowded}'),
      )
  ) %>% 
  st_transform(4269)

# joined
```


```{r echo=FALSE, fig.height=7, fig.width=9, message=FALSE, warning=FALSE}
pal <- colorNumeric("Reds", domain = joined$pct)

leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  setView(-118.29255128780585, 34.044260030549715, zoom = 13) %>% 
  addPolygons(
    data = joined,
    fillColor = ~pal(joined$pct),
    fillOpacity = 0.50,
    color = '#ddd',
    weight = 1,
    popup = joined$popup,
    highlightOptions = highlightOptions(color = "black", weight = 2, bringToFront = TRUE)
  )
```